export const assignmentsText = {
	title: 'Assignments',
	description: 'Choose an available ride and review the details of trips you have accepted.',
	availableTitle: 'Available bookings',
	availableEmpty: 'No bookings available right now.',
	acceptedTitle: 'My assignments',
	acceptedEmpty: 'You have not accepted any bookings yet.',
	acceptLabel: 'Accept',
	acceptPendingLabel: 'Accepting…',
	scheduleConflict: 'Conflicts with your schedule.',
	duration: (minutes: number) => `${minutes} min`,
	parentContact: 'Parent contact',
	phoneUnavailable: 'Phone number not provided',
	notes: 'Notes',
	noNotes: 'No notes provided.',

	notVerifiedError: 'Your profile is not verified yet.',
	notAvailableError: 'This booking is no longer available.',
	childConflictError: 'This child already has a booking at that time.',
	caregiverConflictError: 'You already have a booking at that time.',
	saveError: 'Something went wrong. Please try again.',
} as const;
