export const tripText = {
	statusLabels: {
		SCHEDULED: 'Scheduled',
		EN_ROUTE_TO_SCHOOL: 'On the way to school',
		CHILD_PICKED_UP: 'Child picked up',
		AT_ACTIVITY: 'At the activity',
		EN_ROUTE_HOME: 'On the way home',
		COMPLETED: 'Completed',
		CANCELLED: 'Cancelled',
	},
	actionLabels: {
		EN_ROUTE_TO_SCHOOL: 'Start the trip',
		CHILD_PICKED_UP: 'Confirm pickup',
		AT_ACTIVITY: 'Arrived at the activity',
		EN_ROUTE_HOME: 'Head home',
		COMPLETED: 'Complete the trip',
		CANCELLED: 'Cancel the trip',
	},
	pinLabel: 'Pickup code',
	pinHint: 'Ask the parent for the six-digit code.',
	pendingLabel: 'Saving…',
	pageTitle: 'Trip details',
	currentStatus: 'Current status',
	route: 'Route',
	availableActions: 'Available actions',
	openTrip: 'Open trip',
	tripStatus: 'Trip status',
	eventLog: 'Trip history',
	eventTime: 'Time',
	eventAction: 'What happened',
	eventActor: 'Who did it',
	eventPickupConfirmed: 'Pickup confirmed',
	eventUpdated: 'Trip updated',
	pinShareHint: 'Share this code with your caregiver at pickup.',
	caregiverView: 'Update the trip as each handoff and stop happens.',
	unknownActor: 'System',
	notFoundError: 'This trip is not available.',
	invalidTransitionError: 'This action is no longer possible.',
	versionConflictError: 'The trip has changed. Refresh and try again.',
	invalidPinError: 'That code is not correct.',
	missingKeyError: 'Something went wrong. Please try again.',
	saveError: 'Something went wrong. Please try again.',
} as const;
